site_name: followthemoney
repo_url: https://github.com/opensanctions/followthemoney

theme:
  name: material
  logo: /public/logo.svg
  favicon: /public/favicon.png
  palette:
    primary: custom
    accent: custom
  extra_css: [stylesheets/extra.css]

extra:
  social:
    - icon: material/forum
      link: https://discuss.opensanctions.org/
    - icon: material/github
      link: https://github.com/opensanctions/followthemoney
    - icon: material/web
      link: https://www.followthemoney.tech

plugins:
  - autorefs
  # - social
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: true
            show_object_full_path: false

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Concepts:
      - Introduction: concepts/index.md
      - Entities: concepts/entities.md
      - References: concepts/references.md
      - Streams: concepts/streams.md
  - Model:
      - Property types:
          - Property types: model/types/index.md
          - Country: model/types/country.md
          - Dates: model/types/date.md
