site_name: followthemoney
repo_url: https://github.com/opensanctions/followthemoney

theme:
  name: material
  logo: /public/logo.svg
  favicon: /public/favicon.png
  palette:
    primary: custom
    accent: custom
  extra_css: [stylesheets/extra.css]

extra:
  social:
    - icon: material/forum
      link: https://discuss.opensanctions.org/
    - icon: material/github
      link: https://github.com/opensanctions/followthemoney
    - icon: material/web
      link: https://www.followthemoney.tech

plugins:
  - autorefs
  # - social
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: true
            show_object_full_path: false
          inventories:
            - http://rigour.followthemoney.tech/objects.inv

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Concepts:
      - Introduction: docs/index.md
      - Command line: docs/cli.md
      - Mappings: docs/mappings.md
      - Entity fragmentation: docs/fragments.md
      - Python API: docs/api.md
      - FAQ: docs/faq.md
      - Custom schema: docs/custom.md
  - Model:
      - Property types:
          - Overview: explorer/types/index.md
          - Country: explorer/types/country.md
          - Dates: explorer/types/date.md
  - Python API:
      - Introduction: python/index.md
      - Model: python/model.md
      - Schema: python/schema.md
      - EntityProxy: python/proxy.md
  - Community:
      - Credits: docs/credits.md
